# Generated by Django 4.2.7 on 2023-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
