# Generated by Django 4.2.7 on 2023-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_account_email_alter_account_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='confirmPassword',
            new_name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
