# Generated by Django 4.2.7 on 2023-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_blogs_donations_message_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blogTitle', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='albums/')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
